version: "2"

linters-settings:
  govet:
    enable-all: true
  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
