name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest

    - name: Benchmark
      run: go test -bench=. ./...
